### ISSUE TITLE
Instrument to generate text representation of lnurl 

### ISSUE THREAD

**Issue by altaraven** [yanascz/lnurld#1]
Please help me to understand if this package can generate a lnurl as string like 
"lnurl1dp68gurn....."

I assume that I just need to encode the url
`https://nakamoto.example/.well-known/lnurlp/satoshi`
but I dont know if I should do it manually or there is a way to receive it from lnurl daemon?

**Comment by yanascz** [comment]
Not sure I understand... What is your use case? Why do you need the URL?

**Comment by altaraven** [comment]
I have a web application written in php. I already have LND and btc node installed and working. Also I installed and configured this daemon (lnurld). Seems like its working correctly too.

I want to offer my users two payment methods for Lightning payments:
1) Invoice (generated by LND via its api). Example - `lnbc500u1p3...`
2) Lnurl. Example - `lnurl1dp68gurn...`

So users can copy-paste 1) or 2) into their wallets and make payments
Thats all.
I just want to know if I can generate 2) with this package or I need to encode the url myself (e.g. in php)

**Comment by yanascz** [comment]
Why not allow them to scan a QR code? If they visit your website on their laptop and want to pay using their phone, it's IMO the best UX option available. If they visit your website on their phone, they may copy the QR content if they long tap the QR code image (at least on iOS):

![IMG_1122](https://user-images.githubusercontent.com/37251117/230079003-88e505ac-86b3-4ebd-9a5c-6405bbdd291a.PNG)
![IMG_1123](https://user-images.githubusercontent.com/37251117/230079184-0344fefc-b2ee-4c59-b31a-070012113231.PNG)

If you already have a domain, e.g. `altaraven.example`, and an `lnurld` account called `altaraven`, you may just share `altaraven@altaraven.example` with them and let their wallet + `lnurld` to do the magic for you. See https://lightningaddress.com for more details.

Anyway, if you still want the QR code content, you may extract it from the QR code and use it in your website. Once you set up your `lnurld` account, its value won't change.

**Comment by altaraven** [comment]
Thank you.
Sure, QR code can be the third option, I do understand that most LN wallets support it. But currently I have my customer requirement to have a text representation of lnurl.

At the end, I just decided to encode lnurl myself via php

I just researched your code a little bit and have a question. You encode this url
`actualLnUrl := scheme + "://" + host + "/ln/pay/" + accountKey`
Some wallets encode 
`.../.well-known/lnurlp...`
What is the difference between them?

**Comment by yanascz** [comment]
The `.well-known` variant is used for LN addresses as described in https://github.com/lnurl/luds/blob/luds/16.md. For an ordinary LNURL-pay you may use whatever URL you like, if I understand the specification correctly. And since the URL is shorter without the `.well-known` part, the corresponding QR code needs to encode less data.

So everything solved? Can I close the issue now?

**Comment by altaraven** [comment]
Yes, thank you.
