### ISSUE TITLE
NIP-57 support or bad config?

### ISSUE THREAD

**Issue by theLockesmith** [yanascz/lnurld#2]
I just switched away from lnme because it looks like they don't support NIP-57. While I got lnurld working and at least accepting zaps, I'm told that they're not coming through as zaps.

Is this a problem with my config or is NIP-57 not supported?

**Comment by yanascz** [comment]
👋 NIP-57 is currently not supported. 😕 I've got it somewhere in my TODO list but I don't think I'll get to it any time soon. Anyway, while investigating the requirements and looking for existing libraries, I came across [lnd-nostr-zapper](https://github.com/hugomd/lnd-nostr-zapper). That might be an option for you at the moment.

**Comment by theLockesmith** [comment]
Thanks for that link, I'll check it out. Cheers!

**Comment by yanascz** [comment]
WIP in branch `nip-57` if you're still interested. 🙂

**Comment by yanascz** [comment]
Implemented in revision fd36f95.
